var field = {
    "type": "college",
    "unit": "feet",
    "total_length": 360,
    "total_width": 160,
    "border_thickness": 6,
    "endzone_depth": 30,
    "goalline_thickness": 0.667,
    "hash_width": 40,
    "line_thickness": 0.333,
    "dash_length": 2,
    "number_height": 6,
    "number_width": 4,
    "number_padding": 1,
    "number_top": 27,
    "goalpost_width": 18.5,
    "crossbar_height": 10,
    "goalpost_height": 30,
    "goalpost_diameter": 0.333
};